# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        # Basic project coverage settings
        target: 80%
        threshold: 1%
        base: auto
        flags:
          - unit
          - integration
        
    patch:
      default:
        # Coverage for new code in PR
        target: 80%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  unit:
    paths:
      - internal/
      - cmd/
    carryforward: false
  
  integration:
    paths:
      - test/integration/
    carryforward: false

ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/*.gen.go"
  - "**/*.pb.go"
  - "vendor/**/*"
  - "docs/**/*"
  - "web/**/*"