// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

const MirrorRuleTable = "Mirror_Rule"

type (
	MirrorRuleAction = string
)

var (
	MirrorRuleActionMirror MirrorRuleAction = "mirror"
	MirrorRuleActionSkip   MirrorRuleAction = "skip"
)

// MirrorRule defines an object in Mirror_Rule table
type MirrorRule struct {
	UUID     string           `ovsdb:"_uuid"`
	Action   MirrorRuleAction `ovsdb:"action"`
	Match    string           `ovsdb:"match"`
	Priority int              `ovsdb:"priority"`
}
