apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ovncp.fullname" . }}
  labels:
    {{- include "ovncp.labels" . | nindent 4 }}
data:
  # API Configuration
  API_PORT: "8080"
  API_HOST: "0.0.0.0"
  
  # Database Configuration
  DB_HOST: {{ include "ovncp.databaseHost" . | quote }}
  DB_PORT: {{ include "ovncp.databasePort" . | quote }}
  DB_NAME: {{ include "ovncp.databaseName" . | quote }}
  DB_USER: {{ include "ovncp.databaseUsername" . | quote }}
  DB_SSL_MODE: {{ .Values.externalDatabase.sslMode | quote }}
  
  # OVN Configuration
  OVN_NORTHBOUND_DB: {{ .Values.ovn.northboundDB | quote }}
  OVN_SOUTHBOUND_DB: {{ .Values.ovn.southboundDB | quote }}
  OVN_TIMEOUT: {{ .Values.ovn.timeout | quote }}
  OVN_MAX_RETRIES: {{ .Values.ovn.maxRetries | quote }}
  
  # Auth Configuration
  AUTH_ENABLED: {{ .Values.api.config.authEnabled | quote }}
  LOG_LEVEL: {{ .Values.api.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.api.config.logFormat | quote }}
  
  # OAuth Configuration
  {{- if .Values.oauth.github.enabled }}
  OAUTH_GITHUB_CLIENT_ID: {{ required "GitHub OAuth client ID is required" .Values.oauth.github.clientId | quote }}
  OAUTH_GITHUB_REDIRECT_URL: {{ required "GitHub OAuth redirect URL is required" .Values.oauth.github.redirectUrl | quote }}
  {{- end }}
  
  {{- if .Values.oauth.google.enabled }}
  OAUTH_GOOGLE_CLIENT_ID: {{ required "Google OAuth client ID is required" .Values.oauth.google.clientId | quote }}
  OAUTH_GOOGLE_REDIRECT_URL: {{ required "Google OAuth redirect URL is required" .Values.oauth.google.redirectUrl | quote }}
  {{- end }}
  
  {{- if .Values.oauth.oidc.enabled }}
  OAUTH_OIDC_CLIENT_ID: {{ required "OIDC client ID is required" .Values.oauth.oidc.clientId | quote }}
  OAUTH_OIDC_REDIRECT_URL: {{ required "OIDC redirect URL is required" .Values.oauth.oidc.redirectUrl | quote }}
  OAUTH_OIDC_ISSUER_URL: {{ required "OIDC issuer URL is required" .Values.oauth.oidc.issuerUrl | quote }}
  OAUTH_OIDC_SCOPES: {{ .Values.oauth.oidc.scopes | quote }}
  {{- end }}