apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovncp.fullname" . }}
  labels:
    {{- include "ovncp.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.api.config.jwtSecret | default (randAlphaNum 32) | quote }}
  {{- if .Values.oauth.github.enabled }}
  oauth-github-client-secret: {{ required "GitHub OAuth client secret is required" .Values.oauth.github.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.google.enabled }}
  oauth-google-client-secret: {{ required "Google OAuth client secret is required" .Values.oauth.google.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.oidc.enabled }}
  oauth-oidc-client-secret: {{ required "OIDC client secret is required" .Values.oauth.oidc.clientSecret | quote }}
  {{- end }}
---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovncp.fullname" . }}-external-db
  labels:
    {{- include "ovncp.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ required "External database password is required" .Values.externalDatabase.password | quote }}
{{- end }}